### ISSUE TITLE
InventoryTabs for Minecraft 1.19

### ISSUE THREAD

**Issue by qualterz** [Andrew6rant/InventoryTabs#13]
Can you release the mod for the latest version of Minecraft, please?

**Comment by Khodyn** [comment]
#14 ❤️

**Comment by Andrew6rant** [comment]
InventoryTabs 0.4.5-1.19.x is released on GitHub, CurseForge, and Modrinth! Sorry again Khodyn, I had notifications off for this repo and missed everything
