### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by Balakay420** [Andrew6rant/InventoryTabs#16]
Please add mod support for the following:

- [Expanded Storage](https://www.curseforge.com/minecraft/mc-mods/expanded-storage)
- [Better Nether](https://www.curseforge.com/minecraft/mc-mods/betternether)
- [Better End](https://www.curseforge.com/minecraft/mc-mods/betterend)
- [Charm](https://www.curseforge.com/minecraft/mc-mods/charm)
- [Dark Enchanting](https://www.curseforge.com/minecraft/mc-mods/dark-enchanting)
For some reason, anvils from better nether/end are compatible already

**Comment by Andrew6rant** [comment]
Version 0.6.0 of InventoryTabs should support all of these mods (except for Expanded Storage). I built a small system that dynamically adds tabs for mod support, but mods that do fun stuff with rendering or datagen might not be supported.

**Comment by Andrew6rant** [comment]
Version 0.7.0 supports all of these mods!
