### ISSUE TITLE
A new idea

### ISSUE THREAD

**Issue by PeakXing** [Andrew6rant/InventoryTabs#18]
Great mod, is it possible to replace the chest icon on the render tab based on how much content the chest is? For example, a chest has observer*64*5, shulker box*10, and dropper*64*4. Then calculate the chest icon based on the maximum amount of a single item. I think this might be more suitable for a situation where a lot of boobs are together.

**Comment by Andrew6rant** [comment]
Unfortunately, I can't make the player read the contents of a closed inventory without making this mod also required on the server as well.

I'd like to keep this mod client-sided. A similar thing that I could do is #27. Checking in-world block/entity positions is possible to accomplish purely on the client
