### ISSUE TITLE
Crash due to probably chests

### ISSUE THREAD

**Issue by Balakay420** [Andrew6rant/InventoryTabs#19]
Hello! I forgot one in my last issue.
 [Probably Chests](https://www.curseforge.com/minecraft/mc-mods/probably-chests) which uses [LibGUI](https://www.curseforge.com/minecraft/mc-mods/libgui)

I got this crash when I opened one of their chests
https://paste.ee/p/LEu6z

**Comment by Andrew6rant** [comment]
Doh! My code checks AbstractChestBlocks to see if they are double chests or not (so you don't have two tabs for one chest), I completely forgot that some chests besides the ender chest do not have the CHEST_TYPE property at all, lol. This will be fixed in 6.0.1.

**Comment by Balakay420** [comment]
thank you!!

**Comment by Andrew6rant** [comment]
version 0.6.1 has been released, for 1.18.x and 1.19.x
