### ISSUE TITLE
Compatibility with Better Recipe Book

### ISSUE THREAD

**Issue by ShaneTRS** [Andrew6rant/InventoryTabs#21]
Inventory Tabs are improperly offset when Better Recipe Book keeps the inventory centered, instead of shifting it to the right.

**Comment by Andrew6rant** [comment]
Alright, I've added BetterRecipeBook compatibility. It will be released soon with some other fixes in version 0.6.1.

**Comment by Andrew6rant** [comment]
version 0.6.1 has been released for 1.18.x and 1.19.x
