### ISSUE TITLE
Remove Techreborn cables

### ISSUE THREAD

**Issue by Geartwo** [Andrew6rant/InventoryTabs#23]
Please stop Techreborn cables from being shown
![image](https://user-images.githubusercontent.com/4224642/175923682-3cd60332-8680-4b72-9b70-a40b733f479c.png)

ID List:
techreborn:copper_cable
techreborn:tin_cable
techreborn:gold_cable
techreborn:hv_cable
techreborn:glassfiber_cable
techreborn:insulated_copper_cable
techreborn:insulated_gold_cable
techreborn:insulated_hv_cable
techreborn:superconductor_cable

**Comment by Andrew6rant** [comment]
I've added tab support for all of TechReborn's machines, the final exclusion list is now:

techreborn:basic_machine_casing
techreborn:advanced_machine_casing
techreborn:industrial_machine_casing
techreborn:creative_solar_panel
techreborn:copper_cable
techreborn:tin_cable
techreborn:gold_cable
techreborn:hv_cable
techreborn:glassfiber_cable
techreborn:insulated_copper_cable
techreborn:insulated_gold_cable
techreborn:insulated_hv_cable
techreborn:superconductor_cable
techreborn:resin_basin
techreborn:dragon_egg_syphon
techreborn:lightning_rod
techreborn:water_mill
techreborn:wind_mill
techreborn:drain
techreborn:lsu_storage
techreborn:lv_transformer
techreborn:mv_transformer
techreborn:hv_transformer
techreborn:ev_transformer
techreborn:alarm
techreborn:lamp_incandescent
techreborn:lamp_led
techreborn:computer_cube

Should be released in version 6.0.2.

**Comment by Andrew6rant** [comment]
I decided to go all the way and add a config system. so other mods will also be supported. This is implemented in version 0.7.0
