### ISSUE TITLE
Incompatibility with EasierChests

### ISSUE THREAD

**Issue by Baconbacon123** [Andrew6rant/InventoryTabs#24]
When used with EasierChests(https://www.curseforge.com/minecraft/mc-mods/easierchests) the tabs show properly, but clicking on any of them causes them all to disappear.

**Comment by Andrew6rant** [comment]
Yeah, any mod that does fancy stuff with inventory rendering is not going to display InventoryTabs' tabs. I'll look into getting the two mods to play nice

**Comment by Andrew6rant** [comment]
I figured out a method (released in 0.7.0) that should hopefully support all mod's custom rendering. EasierChests works but there is a little bit of overlapping (I'll address this later)
