### ISSUE TITLE
Top row of Tabs overlap with gui, looks ugly with traslucent gui resource packs

### ISSUE THREAD

**Issue by CodeF53** [Andrew6rant/InventoryTabs#25]
![image](https://user-images.githubusercontent.com/37855219/176235592-fcb60687-d363-4e7c-8a09-49177f8a7e6b.png)

I guess this comes from a stylistic choice to have the active tab a bit higher than the other tabs.
Perhaps you could add an option to disable this?

**Comment by Andrew6rant** [comment]
I'll look into removing the overlap. Can you send me a link to that resource pack, so I can test it?

**Comment by CodeF53** [comment]
https://github.com/CodeF53/AquaHUD

May require
https://modrinth.com/mod/semitranslucency

**Comment by Andrew6rant** [comment]
Alright, I've managed to remove the overlap. I also added translucency support for InventoryTabs' GUI elements.

![AquaHUD InventoryTabs](https://user-images.githubusercontent.com/57331134/176809838-1561442f-22b3-41c9-a87c-2e12af6dff14.png)

I'll release the new version soon, if you want to use it now you can just grab the latest GitHub Action's run: https://github.com/Andrew6rant/InventoryTabs/actions
