### ISSUE TITLE
It shows Sculk Catalyst as option 😆

### ISSUE THREAD

**Issue by ghost** [Andrew6rant/InventoryTabs#26]
![2022-06-30_00 19 49](https://user-images.githubusercontent.com/75373609/176677497-a38959c6-33ce-452b-920a-e0c754715d9a.png)

**Comment by Andrew6rant** [comment]
Oops! This mod dynamically creates tabs for any block that is an instance of BlockEntityProvider, and I forgot to make exceptions for Sculk Catalysts and Sculk Shriekers because I mostly develop in 1.18.x. This has been fixed, and will be live when the next update drops.

**Comment by ghost** [comment]
Thank you for the fast response - awesome 🥰
(I love this this mod.)

**Comment by Andrew6rant** [comment]
Thank you! This is fixed in 0.7.0
