### ISSUE TITLE
[Feature Request] Change Chest Icon based on nearby item frames

### ISSUE THREAD

**Issue by CodeF53** [Andrew6rant/InventoryTabs#27]
Given Chests that have item frames on them, render the item in the item frame instead of the chest icon

![image](https://user-images.githubusercontent.com/37855219/176761948-535f5e7d-fddc-4e56-8d69-a68c47717a3c.png)

![image](https://user-images.githubusercontent.com/37855219/176762433-5d25fa60-062b-4f4f-b378-e5d3bcdd6dac.png)

**Comment by Andrew6rant** [comment]
Ooh, I really like this idea. I'll look into implementing it in the future. For now, you can rename your inventories to get a slightly similar effect

**Comment by Andrew6rant** [comment]
I've started work on this feature. Right now, putting an item in an item frame near a chest will now display that item on the tab, but the item frame detection isn't the most efficient and it can only detect item frames if they are spaced out a little.

![InventoryTabs_Itemframe](https://user-images.githubusercontent.com/57331134/180085681-d7b257a5-bdff-4269-b1a3-289c17b3a654.gif)

**Comment by Andrew6rant** [comment]
I've refined the item frame detection down and gotten this feature working for double chest hitboxes!

![InventoryTabs-nearby-item-frames](https://user-images.githubusercontent.com/57331134/180107483-11429056-8e99-4529-ad7d-7091032fb9aa.gif)

It is in release 0.8.1.

**Comment by CodeF53** [comment]
Empty item frames make chests not have an icon at all?
![image](https://user-images.githubusercontent.com/37855219/180112229-5bf7e893-1ac0-45c1-96ea-53b3f368e4d3.png)

**Comment by Andrew6rant** [comment]
Yeah, that was intentional. Wasn't sure what icon to use (item frame item, regular chest, no icon, etc), so I just left it use the result of `ItemFrameEntity.getHeldItemStack()`. Is there something you'd rather the icon be?

**Comment by CodeF53** [comment]
Just felt a bit odd, maybe later on add an option to show it as a chest?

**Comment by Andrew6rant** [comment]
Yeah I can change it to do that. Didn't imagine anyone would use empty item frames on a chest, haha
