### ISSUE TITLE
[Bug] Duplicate entries show up in GUI

### ISSUE THREAD

**Issue by PanoptesDreams** [Andrew6rant/InventoryTabs#30]
In this room there is one bed, but there are two bed icons in the GUI

GUI with two bed icons showing:
![GUI with two bed icons showing](https://user-images.githubusercontent.com/55162814/176999579-fa6b71c2-2d8d-4f1a-8601-4f23d635d98f.png)

Only one bed
![Only one bed](https://user-images.githubusercontent.com/55162814/176999546-138bf01b-912d-453b-ba0d-a31f3b77fc08.png)

Inventory Tabs 0.7.0
Fabric API 0.53.4
Minecraft 1.18.2
Java MSOpenJDK amd64 17.0.3

Mods:
  [✔️] 3dskinlayers-fabric-1.4.5-mc1.18.2
  [✔️] achievementplates-1.18.2-1.6.1
  [✔️] AdvancedCompass-fabric-1.18.2-1.2.7
  [✔️] AdvancementPlaques-1.18.2-fabric-1.4.5
  [✔️] agb-1.18-1.0.3
  [✔️] amecs-1.3.8+mc.1.18.2
  [✔️] Amplified_Nether_v1.1.1
  [✔️] appleskin-fabric-mc1.18.2-2.4.0
  [✔️] architectury-4.4.68
  [✔️] armor-stand-swap-1.0.2
  [✔️] ArmorSoundTweak-5.0.0-fabric
  [✔️] auto_third_person-1.18-1.1.0
  [✔️] auudio_fabric_1.0.3_MC_1.18-1.18.2
  [✔️] AxesAreWeapons-1.5.1-fabric-1.17.1
  [✔️] axolotl-item-fix-1.1.3
  [✔️] badpackets-fabric-0.1.2
  [✔️] balm-fabric-3.0.0+0
  [✔️] BedBenefits-Fabric-1.18.2-6.0.2
  [✔️] beehive-tooltips-fabric-1.4.2
  [✔️] Better-Enchantment-Boosting-1.2.0
  [✔️] BetterF3-1.2.5-Fabric-1.18.2
  [✔️] BetterResourcePackSorting-1.1.1
  [✔️] BetterThirdPerson-Fabric-1.18.2-1.7.3
  [✔️] BiomeParticleWeather-2.4.7
  [✔️] blur-2.4.1
  [✔️] boatcontainer-1.2.0-1.18
  [✔️] boneequipment-fabric-1.18.2-v1.0.1
  [✔️] Bookshelf-Fabric-1.18.2-13.1.16
  [✔️] brb-1.18.2-fabric-1.5.6
  [✔️] cammies-minecart-tweaks-1.5
  [✔️] camp-fires-cook-mobs-1.2.4+MC1.18-1.18.2
  [✔️] chat_heads-0.6.0-fabric-1.18.1
  [✔️] chipped-1.2
  [✔️] CleanView-1.18.2-v1-fabric
  [✔️] clear-skies-fabric-mc118-2.0.92
  [✔️] cloth-config-6.2.62-fabric
  [✔️] Clumps-fabric-1.18.2-8.0.0+8
  [✔️] Coins-Fabric-1.18.2-7.0.1
  [✔️] collective-fabric-1.18.x-4.26
  [✔️] connected-doors-1.1+1.18
  [✔️] Controlling-fabric-1.18.2-9.0+19
  [✔️] copperlamp-2.1.0
  [✔️] craftingtweaks-fabric-1.18-13.0.0
  [✔️] crawl-0.10.6
  [✔️] creeperoverhaul-1.18.2-1.3.1-fabric
  [✔️] Croptopia-1.18.2-FABRIC-2.0.3
  [✔️] cryingportals-fabric_1.18.x-1.2
  [✔️] cullleaves-2.3.2
  [✔️] custom-lan-1.18.2-v2.0.1
  [✔️] customfov-fabric-1.4.1-1.18.1
  [✔️] darkness-fabric-mc118-2.0.91
  [✔️] dashloader-4.0.0
  [✔️] DeathKnell-Fabric-1.18.2-3.0.2
  [✔️] DetailArmorBar-2.6.2+1.18-fabric
  [✔️] DistantHorizons-1.6.3a-1.18.2
  [✔️] DraggableResourcePacks-2.0.0
  [✔️] dragonloot-1.1.0
  [✔️] DripSounds-1.18-0.3.0
  [✔️] duckling-1.0.5-fabric
  [✔️] dynamic-fps-2.1.0
  [✔️] dynamiccrosshair-3.0.1+1.18.2
  [✔️] dynamiccrosshair-compat-1.0+1.18.2
  [✔️] EasyMagic-v3.3.0-1.18.2-Fabric
  [✔️] ecologics-FABRIC-1.18.2-1.5.4
  [✔️] effective-1.2.1
  [✔️] elytratrinket-fabric-3.0.0-1.18.1
  [✔️] enchancement-1.18-18
  [✔️] EnchantmentDescriptions-Fabric-1.18.2-10.0.3
  [✔️] enhanced_attack_indicator-1.0.3+1.18
  [✔️] enhancedblockentities-0.7+1.18.2
  [✔️] entityculling-fabric-mc1.18-1.5.1
  [✔️] EquipmentCompare-1.18.2-fabric-1.2.12
  [✔️] exlineawnings-fabric-1.18.2-v1.0.3
  [✔️] fabric-allay-1.18.1-4.0.0
  [✔️] fabric-api-0.53.4+1.18.2
  [✔️] fabulousclouds-0.3.0
  [✔️] fallingleaves-1.11.1+1.18.2
  [✔️] fallthroughslime-fabric_1.18.x-1.4
  [✔️] fastopenlinksandfolders-1.1.1
  [✔️] Fireplace-Lib-6.3.1+1.18.2
  [✔️] firstperson-fabric-2.1.0-mc1.18-pre1
  [✔️] ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric
  [✔️] forgetmechunk-1.18.X-1.0.3
  [✔️] geckolib-fabric-1.18.2-3.0.35
  [✔️] gilded-1.18-1.0.1
  [✔️] global_packs-fabric-1.18.2-1.12.2
  [✔️] guard-villagers-fabric-1.18.2-1.0.14
  [✔️] HealthOverlay-1.18.2-6.2.4
  [✔️] here-be-no-dragons-1.0.0
  [✔️] Highlighter-1.18-fabric-1.1.2
  [✔️] hoetweaks-fabric_1.18.x-1.4
  [✔️] holograms-1.3.1+1.18.2
  [✔️] icarus-1.11
  [✔️] Iceberg-1.18.2-fabric-1.0.38
  [✔️] ihgm-1.0.1
  [✔️] illuminations-1.10.4
  [✔️] immersive_weathering-2.5.3
  [✔️] improved-fire-overlay-1.18.2-v1.2
  [✔️] indicatia-mc1.18.2-v6.2.0-fabric
  [✔️] indium-1.0.3+mc1.18.2
  [✔️] infusion-table-mod-1.1.0
  [✔️] interactic-0.1.10+1.18
  [✔️] InventoryProfilesNext-fabric-1.18.2-1.4.0
  [✔️] inventorytabs-0.7.0-1.18.x
  [✔️] InvMove-1.18-0.7.0-Fabric
  [✔️] ironchests-2.0.3-fabric
  [✔️] ItemBorders-1.18-fabric-1.1.5
  [✔️] itemflexer-1.2.4
  [✔️] Jade-1.18.2-fabric-5.99.5
  [✔️] justmobheads-fabric_1.18.x-5.4
  [✔️] kleeslabs-fabric-1.18-11.0.0
  [✔️] konkrete_fabric_1.3.3-1_MC_1.18-1.18.2
  [✔️] lambdabettergrass-1.2.3+1.18
  [✔️] lazy-language-loader-0.3.0
  [✔️] lazydfu-0.1.2
  [✔️] LeftHanging-fabric-1.18.2-3.2.0.2
  [✔️] LegendaryTooltips-1.18.2-fabric-1.2.5
  [✔️] lenientstacksize-1.3.0
  [✔️] libmultipart-all-0.7.2
  [✔️] lithium-fabric-mc1.18.2-0.7.10
  [✔️] lucys-sloths-1.0
  [✔️] MagicalForest-fabric-1.18.2-2.0.3
  [✔️] mcw-bridges-2.0.3fabric-mc1.18.2
  [✔️] mcw-roofs-2.1.2fabric-mc1.18.2
  [✔️] merenc-fabric-1.18.2-v1.4
  [✔️] modmenu-3.2.3
  [✔️] netherite-nuggets-1.4.1+1.18.2
  [✔️] netherportalspread-fabric_1.18.x-5.7
  [✔️] nmuk-1.0.1+mc1.18-pre1
  [✔️] notenoughanimations-fabric-1.6.0-mc1.18.2
  [✔️] onsoulfire-1.18-3
  [✔️] paginatedadvancements-1.0.1
  [✔️] pal-1.5.1
  [✔️] passiveendermen-fabric_1.18.x-2.3
  [✔️] Patchouli-1.18.2-67-FABRIC
  [✔️] Pehkui-3.3.3+1.14.4-1.19.1
  [✔️] physics-mod-2.7.3-mc-1.18.2-fabric
  [✔️] powershot-1.4.0-1.18.2-fabric
  [✔️] PresenceFootsteps-1.5.1
  [✔️] PuzzlesLib-v3.3.5-1.18.2-Fabric
  [✔️] quickshulker-1.3.6-1.18
  [✔️] recipecache-0.2.1-1.17.1
  [✔️] reroll-1.5.0-1.18.2
  [✔️] RingsOfAscension-1.18.2-1.0.1
  [✔️] ruined-equipment-1.4.1+1.18.2
  [✔️] saplanting-fabric-1.18.2-1.1.1
  [✔️] seamless-loading-screen-1.4.0+1.18.2
  [✔️] shulkerboxtooltip-3.0.10+1.18.2
  [✔️] slipperywalls-1.0.0+1.17
  [✔️] SmoothCoasters-1.18.2-v1
  [✔️] SmoothScrollingEverywhere-3.0.4
  [✔️] snowyleavesplus-0.1.2
  [✔️] sodium-fabric-mc1.18.2-0.4.1+build.15
  [✔️] solid_mobs-1.0-mc1.18.x
  [✔️] soundcategories-1.2.2+1.18
  [✔️] soundphysics-fabric-1.18.2-1.0.6
  [✔️] spyglass-improvements-1.2+mc1.18.2+fabric
  [✔️] starlight-1.0.2+fabric.89b8d9f
  [✔️] TaxFreeLevels-1.3
  [✔️] telepistons-1.0.2
  [✔️] TerraBlender-fabric-1.18.2-1.1.0.102
  [✔️] The_Graveyard_1.9_(FABRIC)_for_1.18.2
  [✔️] The_Graveyard_Biomes_1.1_(FABRIC)_for_1.18.2
  [✔️] the-box-trot-1.3
  [✔️] TinySkeletons-v3.2.1-1.18.2-Fabric
  [✔️] tooltipfix-1.0.4-1.18
  [✔️] torchhit-1.18.2-2.0.0.0-fabric
  [✔️] travelers-backpack-1.18.2-7.1.0
  [✔️] trinkets-3.3.1
  [✔️] Unforgiving-Void-3.1.3+1.18.2
  [✔️] veinmining-fabric-0.0.12-1.18.2
  [✔️] villagernames-1.18.2-4.0.4
  [✔️] visuality-0.4.2
  [✔️] VisualWorkbench-v3.3.0-1.18.2-Fabric
  [✔️] walljump-fabric-1.4.7+1.18.2
  [✔️] wanderingcollector-1.1.2+mc1.18.2
  [✔️] WaveyCapes-fabric-1.2.0-mc1.18
  [✔️] window_title_changer-2.1.1-1.18
  [✔️] WindowedFullscreen-1.18-fabric-1.0.1
  [✔️] WinterCoats+v1.0+MC1.18
  [✔️] wolves-with-armor-1.7.1-1.18.2
  [✔️] wooltweaks-fabric_1.18.x-1.5
  [✔️] worldtime-1.18.2-fabric0.47.10-1.3.1

Side question, are there supposed to beds in the UI?

**Comment by Andrew6rant** [comment]
This will be fixed in the next update.

The reason there are two beds is because one bed is made up of two block entities. I was planning on making a TabProvider so that a single bed tab would appear only when it is a valid time to sleep, but later decided against it as InventoryTabs should be for inventories only.

I then forgot to exclude the bed block tab haha

**Comment by Andrew6rant** [comment]
Fixed in 0.8.0

**Comment by PanoptesDreams** [comment]
> This will be fixed in the next update.
> 
> The reason there are two beds is because one bed is made up of two block entities. I was planning on making a TabProvider so that a single bed tab would appear only when it is a valid time to sleep, but later decided against it as InventoryTabs should be for inventories only.
> 
> I then forgot to exclude the bed block tab haha

That's very interesting, I totally forgot to consider the bed is 2 blocks. Scratched my head and had a laugh about it for a while.

I'm glad it's being removed :)
