### ISSUE TITLE
Ignore `autopath:path` block by default

### ISSUE THREAD

**Issue by qualterz** [Andrew6rant/InventoryTabs#32]
Do not display tabs for path blocks from [Automatic-Path](https://github.com/lebonq/Automatic-Path) mod

**Comment by Andrew6rant** [comment]
Fixed in 0.8.0.

This version has a new tag, `#inventorytabs:mod_compat_blacklist`, in addition to the player config. Mod makers or modpack developers can choose to add to the tag, or the config itself.
