### ISSUE TITLE
Shriekers have an inventory tab

### ISSUE THREAD

**Issue by baobuh** [Andrew6rant/InventoryTabs#33]
Shriekers are not chests but they still have their own tabs, I think this is a bug

**Comment by Andrew6rant** [comment]
What version of InventoryTabs are you using? This should've been fixed in 0.7.0

**Comment by Andrew6rant** [comment]
I'm going to close this issue now that 0.8.0 is released because it is fixed. Feel free to reopen this if you can reproduce the issue using 0.7.0 or 0.8.0.
