### ISSUE TITLE
Config Blacklist does not accept Tagged item

### ISSUE THREAD

**Issue by ardissaps** [Andrew6rant/InventoryTabs#38]
I use tag it does not work, I can confirm by the tooltip that my [KubeJS Tag Event](https://mods.latvian.dev/books/kubejs/page/tageventjs) setting added the tag to the item correctly.

![image](https://user-images.githubusercontent.com/82106625/180345181-d462f677-2fa4-4d5b-9282-af14734150f7.png)
![image](https://user-images.githubusercontent.com/82106625/180345239-729cb8be-4158-4ccc-a454-1440f2767f6a.png)

(your mod [Stacker](https://modrinth.com/mod/stacker) item does accept tag with procedure like above, and it works, just wish could do the same with Inventory Tabs)

Additional Information : it works if individually added like "platform:ramp", but wish can be simplified with tag because it can filled to many lines in config for mods like Create which all the item need to be blacklisted currently.

**Comment by Andrew6rant** [comment]
I haven't used KubeJS before, but I believe the blacklist tag for InventoryTabs should be `#inventorytabs:mod_compat_blacklist`

**Comment by ardissaps** [comment]
Or another alternative allow editing the file directly in game so we can use text software alongside with minecraft windows looking at their item id.

Currently if we use text editor while opening the game, it does not apply to current setting.
![image](https://user-images.githubusercontent.com/82106625/180350085-9de373e0-8fa1-4304-8a95-01f5c8d31813.png)




> #inventorytabs:mod_compat_blacklist

i will try this.

**Comment by ardissaps** [comment]
> I haven't used KubeJS before, but I believe the blacklist tag for InventoryTabs should be `#inventorytabs:mod_compat_blacklist`

I added #inventorytabs:mod_compat_blacklist tag on item but the tab still displayed.

**Comment by Andrew6rant** [comment]
What mod and item is it? I can try and take a look

**Comment by ardissaps** [comment]
Farmer Delight Stove
![2022-07-22_10 08 13](https://user-images.githubusercontent.com/82106625/180354414-e9348b14-5cc1-40e5-a40b-6bf38c6616aa.png)
![image](https://user-images.githubusercontent.com/82106625/180354432-8d8d4a32-9e10-4a51-a569-c6ba0d4214a8.png)
![image](https://user-images.githubusercontent.com/82106625/180354485-a4459255-6610-4bdc-857e-6d5a7a68b05b.png)

**Comment by ardissaps** [comment]
It is same for all mods, the setting just ignore #tag.

**Comment by Andrew6rant** [comment]
I think I see your problem, the tags are supposed to be block tags, not item tags

**Comment by ardissaps** [comment]
> I think I see your problem, the tags are supposed to be block tags, not item tags

I see, thank you for the information! I will try again and ask if I found problem.

**Comment by ardissaps** [comment]
Yes, it worked now, thank you very much!

**Comment by Andrew6rant** [comment]
No problem! The reason I used block tags is because I analyze the registry for block entities.

> Or another alternative allow editing the file directly in game so we can use text software alongside with minecraft windows looking at their item id.

I'm not sure if I will be able to allow players to edit the actual config JSON without restarting the game, but I will look into it. For now, you can enable the debug option to print every single block ID that has a tab associated with it. Should help identifying IDs you'd like to remove
