### ISSUE TITLE
[Feature Request] Align player inventory to the center, when crafting recipes book is opened

### ISSUE THREAD

**Issue by leon0399** [Andrew6rant/InventoryTabs#51]
When crafting recipes books is open, it causes shifting of tabs, when changing between tabs (see screenshots below). 

My idea is to align main player inventory to the center, when this book is opened

| State | Screenshot |
| :----- | :-----------: |
| Crafting book is open | ![2022-08-18_18 15 36](https://user-images.githubusercontent.com/1759654/185431440-123882a0-099e-42ca-8687-d637605090fb.png) |
| Crafting book is closed | ![2022-08-18_18 15 41](https://user-images.githubusercontent.com/1759654/185431757-5f02e4ea-9aa7-4468-aadb-0c7cc84d8d3f.png) |

**Comment by Andrew6rant** [comment]
That feature is a bit out of scope for this mod. You can use the mod "Better Recipe Book" with the option "Keep crafting screens centered" selected to achieve this.
