### ISSUE TITLE
[Feature Request] Creative Integration

### ISSUE THREAD

**Issue by Julienraptor01** [Andrew6rant/InventoryTabs#7]
Please make it so that in creative we have a small arrow like we have to many tabs in survival to go trhough inventories.
It's already possible to open the menu in creative by simply openeing some chest as you can see below.
![image](https://user-images.githubusercontent.com/49841713/163831099-fa92a5af-fa4d-4cfe-b2ad-b75a002b62ee.png)

**Comment by Andrew6rant** [comment]
Unfortunately, I tried to add Creative mode support but the tabs kept overlapping with the regular creative tabs, and it was a bit buggy. I'm going to close this as wontfix for now, InventoryTabs is really meant for survival
