### ISSUE TITLE
Possibly incompatible with `You're in Grave Danger`

### ISSUE THREAD

**Issue by filcuk** [Andrew6rant/InventoryTabs#76]
Crash report: https://crashy.net/uqnweEeqc5SuScwqDAI7
[You're in Grave Danger](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)

If in proximity of a grave that contains any items from user's inventory (i.e. not empty), the client will crash.

**Comment by sleepingdragoninn** [comment]
Try the TQuilt jar [1.18](https://github.com/sisby-folk/mc-packs/blob/quilt_1.18.2/mods/inventorytabs-0.9.0-beta-1.18.x.jar) [1.19](https://github.com/sisby-folk/mc-packs/blob/quilt_1.19.2/mods/inventorytabs-0.9.0-beta-1.19.x.jar).

I made a PR in september which hasn't gotten a release, and it fixed an issue where if the player died near tab providers, the game would crash.

**Comment by filcuk** [comment]
Thank you, I believe that has since been merged.
Tested and issue appears to be resolved.
