### ISSUE TITLE
[Feature Request] Config Menu

### ISSUE THREAD

**Issue by Julienraptor01** [Andrew6rant/InventoryTabs#8]
I've noticed that there is a config file but what does the option mean ?

**Comment by Andrew6rant** [comment]
The `doSightChecksFlag` option checks if a block is in the player's line of sight (turning it off allows you to reach blocks through walls). Servers can install this mod to force this check

The `rotatePlayer` option snaps the player's view to each tab's inventory. It is a bit jarring to look at, so it is disabled by default.

The `excludeTab` list is a collection of block id's to NOT display tabs

The `includeTab` list is a collection of block id's to force display tabs

The `debugEnabled` option prints debugging information (mostly for modpack developers, to be used when editing exclude/include lists)
