### ISSUE TITLE
[Bug] Creative Tab

### ISSUE THREAD

**Issue by Julienraptor01** [Andrew6rant/InventoryTabs#9]
When you try to open some chest in creative if the last inventory menu open was your inventory trough the tab and not a chest or a barrel, etc then it will show the player tab instead of the chest or another block tab
![image](https://user-images.githubusercontent.com/49841713/163833359-523a7910-5cbf-4c40-b583-a1dff6007f39.png)

**Comment by Andrew6rant** [comment]
Fixed in 0.7.0
