### ISSUE TITLE
incompatible with 1.19.4

### ISSUE THREAD

**Issue by IFedor-F** [Andrew6rant/InventoryTabs#90]
When will the mod version be released for 1.19.4?

**Comment by EnderKill98** [comment]
The current source code seems to work for 1.19.4 already. Though I noticed a crash caused by it, when attempting to open the Key bind settings.

**Comment by IFedor-F** [comment]
The game also crashes when trying to open inventory in survival next to the chest
https://mclo.gs/8XdOjdf

**Comment by jpeterburs** [comment]
Same issue here game starts and opens worlds as expected. But once I try to open the inventory, the game crashes

**Comment by EnderKill98** [comment]
The crashing on opening e.g. any chest is when trying to use the 1.19.3 version on 1.19.4 afaik. I think the mod allows to be loaded there but is not compatible at all. The current source code in master has some 1.19.4 adjustments already though, which was what I talked about.

**Comment by jpeterburs** [comment]
Did a test with a dev build (compiling it myself with Ubuntu 22.04 LTS and a fresh java install) and it seems to work for me.

Looks like https://github.com/Andrew6rant/InventoryTabs/pull/89 may have done the trick.

**Comment by LuukPlay** [comment]
Waiting for public 1.19.4 update, with crash fix

**Comment by Andrew6rant** [comment]
Oops! I completely forgot about publishing the latest version of this mod. I need to update my Workflows script.

1.19.4 support has been released, thank KJNine for the PRs.
