### ISSUE TITLE
Latest commit (46155ed) causes crash when entering keybinds menu

### ISSUE THREAD

**Issue by 2001herne** [Andrew6rant/InventoryTabs#91]
As in title, commit 46155ed appears to cause a crash when accessing the keybinds menu via [ESC] -> Options -> Controls -> Key Binds. Crash log attached.
[crash-2023-05-01_20.14.16-client.txt](https://github.com/Andrew6rant/InventoryTabs/files/11364937/crash-2023-05-01_20.14.16-client.txt)

**Comment by KJNine** [comment]
PR #93 fixes this
